// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gbjberhxemigrnhyqwvz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdiamJlcmh4ZW1pZ3JuaHlxd3Z6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkyMjQ3MTMsImV4cCI6MjA2NDgwMDcxM30.Lz9WbvVJ6DMoc5LNKeL-TFnPZjm5iUTTq62lT1km9_M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);